module3-task1
htmlacademy-adaptive/1008951-cat-energy-24 pull request #4
Opened 2021-12-03 11:32 UTC by Nikolay-del

2021-12-05 15:46 UTC, redsmoke19 requested changes
Коль ты молодец и в целом не рлохо справился с заданием, хоть и многие вещи ты поторопился делать, потом исправлять придется)
Есть несколько замечний которые нужно исправить:
1. В сборке есть ошибки и тесты она не проходит
2. Не подключены шрифты на страницу
3. Появился горизонатльный скрол на странице главной (убери % в опступе у кнопки в блоке промо)
4. Блок дополнительных товаров на странице каталога не нужно верстать таблицей, верстай обычными тегами, ты с таблицей там напутал сильно

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/promo.scss
> +  padding: 7px 100%;
зачем тут 100% отступ?  Не нужно указывать отступ такой в %

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/global/global.scss
> +  overflow: hidden
пропущена точка с запятой на конце строки

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/promo.scss
> +  width: 249px;
Плохая практика задавать ширину для текста, убери ее

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/program.scss
> +  width: 227px;
Плохая практика задавать ширину для текста, убери ее

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/program.scss
> +.program__line {
зачем тут это нужно ? Вообще нужно убрать этот стиль и тег hr а сделать обычную рамку

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/program.scss
> +  // border-top: 1px solid #d9d9d9;
почему ты решил убрать эту рамку ? Укажи ссылке display block и рамка растянеться на всю ширину

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +    <section class="program container">
container лучше делать отдельным классов внутри секции, и уже в контейнер вкладывать весь контент. Это нужно исправить везде по коду

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +      <div class="advantages__container">
просто container, он должен быть у тебя один класс контейнер который ты будешь использовать для всех секций

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/advantages.scss
> +  width: 199px;
Плохая практика задавать ширину для текста, убери ее

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/example.scss
> +  width: 280px;
Плохая практика задавать ширину для текста, убери ее

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/example.scss
> +  margin: 0 -16px;
зачем тебе тут отрицательные маргины ? Их нужно убрать

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +        <img src="img/before-mobile.png" alt="Кот до функционального питания 'Cat Energy'"
а почему для этой картинки нет класса ? И размеров тоже нет

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +        <img src="img/after-mobile.png" alt="Кот после функционального питания 'Cat Energy'"
нет размеров для картинки

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +        <input type="range" min="1" max="3" id="before-after">
нет класса для инпута

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/cooperation.scss
> +  width: 139px;
убери ширину

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/cooperation.scss
> +  width: 139px;
убери ширину

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +      <hr class="page-footer__line">
убри hr и стилизуй просто рамкой

2021-12-05 15:46 UTC, redsmoke19 commented on source/index.html
> +      <hr class="page-footer__line">
убри hr и стилизуй просто рамкой

2021-12-05 15:46 UTC, redsmoke19 commented on source/catalog.html
> +  <header class="page-header">
Почему тут тег header и почему в него вложен весь контент ?

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/catalog.scss
> +  &--more {
нельзя так на этом проекте вкладывать модификаторы. Пиши их отдельными свойствами

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/catalog.scss
> +  width: 76px;
убери ширину

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/catalog.scss
> +  width: 138px;
не нужна тут фиксированная ширина! Вообще старайся избегать фиксированных широт это плохая практика

2021-12-05 15:46 UTC, redsmoke19 commented on source/sass/components/gift.scss
> +  width: 161px;
убери ширину

2021-12-05 17:09 UTC, Nikolay-del commented on source/sass/global/global.scss
> +  overflow: hidden
Исправил

2021-12-05 17:09 UTC, Nikolay-del commented on source/sass/components/promo.scss
> +  width: 249px;
Исправил

2021-12-05 17:10 UTC, Nikolay-del commented on source/sass/components/program.scss
> +  width: 227px;
Исправил

2021-12-05 19:36 UTC, Nikolay-del commented on source/sass/components/program.scss
> +.program__line {
Исправил

2021-12-05 19:48 UTC, Nikolay-del commented on source/index.html
> +    <section class="program container">
Исправил

2021-12-05 19:48 UTC, Nikolay-del commented on source/sass/components/advantages.scss
> +  width: 199px;
Исправил

2021-12-05 19:49 UTC, Nikolay-del commented on source/sass/components/example.scss
> +  width: 280px;
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/index.html
> +        <img src="img/before-mobile.png" alt="Кот до функционального питания 'Cat Energy'"
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/index.html
> +        <img src="img/after-mobile.png" alt="Кот после функционального питания 'Cat Energy'"
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/index.html
> +        <input type="range" min="1" max="3" id="before-after">
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/sass/components/cooperation.scss
> +  width: 139px;
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/index.html
> +      <hr class="page-footer__line">
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/index.html
> +      <hr class="page-footer__line">
Исправил

2021-12-05 20:07 UTC, Nikolay-del commented on source/catalog.html
> +  <header class="page-header">
Исправил

2021-12-05 20:08 UTC, Nikolay-del commented on source/sass/components/catalog.scss
> +  &--more {
Исправил

2021-12-06 11:30 UTC, Nikolay-del commented on source/sass/components/example.scss
> +  margin: 0 -16px;
Исправил

2021-12-06 11:30 UTC, Nikolay-del commented on source/sass/components/cooperation.scss
> +  width: 139px;
Исправил

2021-12-06 11:31 UTC, Nikolay-del commented on source/sass/components/catalog.scss
> +  width: 138px;
Исправил

2021-12-06 11:31 UTC, Nikolay-del commented on source/sass/components/gift.scss
> +  width: 161px;
Исправил

2021-12-06 12:10 UTC, Nikolay-del commented on source/sass/components/catalog.scss
> +  width: 76px;
Исправил

2021-12-06 12:11 UTC, Nikolay-del commented on source/sass/components/promo.scss
> +  padding: 7px 100%;
Исправил

2021-12-07 03:44 UTC, merged